[package]
name = "ksuinit"
version = "2.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# for elf parsing
goblin = "0.10"
scroll = "0.13"

anyhow = "1"
rustix = { git = "https://github.com/Baka-SU/rustix.git", rev = "4a53fbc", features = ["mount", "fs", "runtime", "system", "process"] }

syscalls = { version = "0.8", default-features = false, features = [
    "aarch64",
    "x86_64",
    "riscv64",
] }

# for kmsg logging
log = "0.4"
kernlog = { git = "https://github.com/Baka-SU/kernlog.rs" }

[patch.crates-io]
libc = { git = "https://github.com/rust-lang/libc", rev = "1a661633f11a261ff9c00b40875ef72f1cbec818" }

[profile.release]
strip = true
lto = true
opt-level = "z"
panic = "abort"
